import React, { useState } from "react";
import { Task, ScheduleItem, UserPrefs } from "../types";
import { Calendar, Sparkles, AlertTriangle, Clock, CalendarDays, ExternalLink, Download } from "lucide-react";

interface ScheduleViewProps {
  tasks: Task[];
  prefs: UserPrefs;
  schedule: ScheduleItem[];
  onSaveSchedule: (schedule: ScheduleItem[]) => void;
  apiKey?: string;
}

export default function ScheduleView({
  tasks,
  prefs,
  schedule,
  onSaveSchedule,
  apiKey,
}: ScheduleViewProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleBuildSchedule = async () => {
    setIsGenerating(true);
    setError(null);

    const activeTasks = tasks.filter((t) => !t.completed);

    try {
      const res = await fetch("/api/gemini/schedule", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-custom-api-key": apiKey || "",
        },
        body: JSON.stringify({
          tasks: activeTasks.map((t) => ({
            id: t.id,
            title: t.title,
            estimated_minutes: t.estimatedDuration,
            priority: t.priority,
          })),
          startHour: prefs.workStartHour,
          endHour: prefs.workEndHour,
          breakPreference: prefs.breakPreference,
        }),
      });

      if (!res.ok) {
        const errData = await res.json();
        throw new Error(errData.error || "Failed to generate schedule.");
      }

      const data = await res.json();
      if (data.result) {
        onSaveSchedule(data.result);
      } else {
        throw new Error("Invalid response format from AI scheduler.");
      }
    } catch (err: any) {
      console.error(err);
      setError(err.message || "An unexpected error occurred while communicating with Gemini.");
    } finally {
      setIsGenerating(false);
    }
  };

  // Helper to generate Google Calendar quick template URLs
  const getGoogleCalendarUrl = (item: ScheduleItem) => {
    const title = encodeURIComponent(item.task_title);
    const details = encodeURIComponent(
      `Planned block via LastMinute AI.\nDuration: ${item.duration_mins} mins.\nType: ${item.type}`
    );

    // Get current date string 20260623
    const datePart = "20260623";

    // Split times (e.g. "09:00 - 10:30")
    const timeParts = item.time.split("-").map((t) => t.trim().replace(":", ""));
    const startTime = timeParts[0];
    const endTime = timeParts[1];

    const dates = `${datePart}T${startTime}00Z/${datePart}T${endTime}00Z`; // Assume UTC for template or standard local
    return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&details=${details}&dates=${dates}`;
  };

  // Helper to export schedule as .ics file
  const handleExportICS = () => {
    if (schedule.length === 0) return;

    const datePart = "20260623";
    let icsContent = "BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//LastMinute AI//NONSGML Daily Schedule//EN\n";

    schedule.forEach((item, index) => {
      const timeParts = item.time.split("-").map((t) => t.trim().replace(":", ""));
      const startTime = timeParts[0] + "00";
      const endTime = timeParts[1] + "00";

      icsContent += "BEGIN:VEVENT\n";
      icsContent += `UID:lastminute-ai-uid-${index}-${Date.now()}\n`;
      icsContent += `DTSTAMP:${datePart}T222614Z\n`;
      icsContent += `DTSTART;TZID=America/New_York:${datePart}T${startTime}\n`;
      icsContent += `DTEND;TZID=America/New_York:${datePart}T${endTime}\n`;
      icsContent += `SUMMARY:${item.task_title}\n`;
      icsContent += `DESCRIPTION:Planned block via LastMinute AI. Duration: ${item.duration_mins} mins.\n`;
      icsContent += "END:VEVENT\n";
    });

    icsContent += "END:VCALENDAR";

    const blob = new Blob([icsContent], { type: "text/calendar;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `LastMinute_AI_Schedule_${datePart}.ics`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white tracking-tight">AI Smart Scheduler</h1>
          <p className="text-xs text-gray-400 font-medium">
            Time-blocked hourly agenda generated by Gemini based on task durations, priorities, and your working window ({prefs.workStartHour} - {prefs.workEndHour})
          </p>
        </div>
        <button
          onClick={handleBuildSchedule}
          disabled={isGenerating}
          className="px-4 py-2 rounded-xl text-xs font-bold text-black bg-accent-indigo hover:bg-accent-indigo/90 hover:scale-[1.02] active:scale-[0.98] transition shadow-lg shadow-accent-indigo/15 flex items-center gap-1.5 cursor-pointer disabled:opacity-50"
        >
          <Sparkles size={14} className={isGenerating ? "animate-spin" : ""} />
          <span>{schedule.length > 0 ? "Regenerate Schedule" : "Build My Schedule"}</span>
        </button>
      </div>

      {error && (
        <div className="p-4 rounded-xl bg-accent-red/10 border border-accent-red/20 text-accent-red text-xs flex gap-2">
          <AlertTriangle size={16} className="shrink-0 mt-0.5" />
          <div>
            <span className="font-semibold">Scheduler execution failed:</span> {error}
          </div>
        </div>
      )}

      {/* SCHEDULE BUILDER MAIN PANEL */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* HOUR-BY-HOUR TIMELINE (2/3 width) */}
        <div className="lg:col-span-2">
          <div className="glass-card rounded-2xl p-6 md:p-8 space-y-6">
            <div className="flex items-center justify-between border-b border-gray-800 pb-4">
              <div className="flex items-center gap-2">
                <CalendarDays size={18} className="text-accent-indigo" />
                <h2 className="text-base font-bold text-white">Today's Timeline</h2>
              </div>
              {schedule.length > 0 && (
                <div className="flex items-center gap-2">
                  <button
                    onClick={handleExportICS}
                    className="px-2.5 py-1.5 rounded-lg border border-gray-700 bg-gray-900/40 text-[11px] font-semibold text-gray-300 hover:text-white hover:bg-gray-850 transition flex items-center gap-1 cursor-pointer"
                    title="Download Calendar ICS file"
                  >
                    <Download size={12} />
                    <span>Export ICS</span>
                  </button>
                </div>
              )}
            </div>

            {isGenerating ? (
              <div className="py-24 text-center space-y-4">
                <div className="flex items-center justify-center gap-1.5 text-accent-indigo">
                  <Sparkles size={20} className="animate-spin" />
                  <span className="text-sm font-bold">Constructing hourly blocked schedule</span>
                  <span className="animate-bounce">.</span>
                  <span className="animate-bounce [animation-delay:0.2s]">.</span>
                  <span className="animate-bounce [animation-delay:0.4s]">.</span>
                </div>
                <p className="text-xs text-gray-400 max-w-xs mx-auto">
                  Gemini is mapping out deep-work periods, scheduling breaks relative to your preferences, and pacing workloads safely.
                </p>
              </div>
            ) : schedule.length === 0 ? (
              <div className="py-16 text-center space-y-4">
                <div className="flex items-center justify-center w-12 h-12 mx-auto rounded-xl bg-gray-900/50 text-gray-400 border border-gray-800">
                  <Clock size={22} />
                </div>
                <div className="max-w-xs mx-auto space-y-1.5">
                  <h3 className="text-xs font-bold text-white">No Schedule Set</h3>
                  <p className="text-[11px] text-gray-400">
                    Your hourly timeline is blank. Click the "Build My Schedule" button to let Gemini map out a customized day.
                  </p>
                </div>
              </div>
            ) : (
              <div className="relative border-l border-gray-800 pl-6 ml-3 space-y-6">
                {schedule.map((item, index) => {
                  const isBreak = item.type === "break";

                  return (
                    <div key={index} className="relative group animate-in fade-in slide-in-from-left-4 duration-200">
                      {/* Timeline Dot Indicator */}
                      <div
                        className={`absolute -left-[31px] top-1 w-2.5 h-2.5 rounded-full border transition duration-300 ${
                          isBreak
                            ? "bg-accent-mint/30 border-accent-mint scale-90"
                            : "bg-accent-indigo/30 border-accent-indigo ring-4 ring-bg-dark"
                        }`}
                      />

                      <div
                        className={`p-4 rounded-xl border transition ${
                          isBreak
                            ? "bg-accent-mint/5 border-accent-mint/10 text-gray-300"
                            : "bg-gray-950/40 border-gray-800 hover:border-gray-700 hover:bg-gray-950/60"
                        }`}
                      >
                        <div className="flex items-start justify-between gap-3">
                          <div className="space-y-1">
                            <div className="flex items-center gap-2">
                              <span className="text-[10px] font-mono font-semibold text-gray-500">
                                {item.time}
                              </span>
                              <span className="text-[9px] text-gray-600">•</span>
                              <span className="text-[10px] text-gray-400 font-medium">
                                {item.duration_mins} mins
                              </span>
                            </div>
                            <h3 className={`text-xs font-bold ${isBreak ? "text-accent-mint" : "text-white"}`}>
                              {item.task_title}
                            </h3>
                          </div>

                          {!isBreak && (
                            <a
                              href={getGoogleCalendarUrl(item)}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="px-2 py-1 rounded-lg bg-gray-900 border border-gray-800 text-[10px] text-gray-400 font-semibold hover:text-white hover:border-gray-700 transition flex items-center gap-1 cursor-pointer shrink-0"
                              title="Sync event directly to Google Calendar"
                            >
                              <ExternalLink size={10} />
                              <span>To Google Cal</span>
                            </a>
                          )}
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        </div>

        {/* SIDE BAR SCHEDULER NOTES (1/3 width) */}
        <div className="space-y-4">
          <div className="glass-card rounded-2xl p-6 space-y-4">
            <h3 className="text-xs font-bold text-white uppercase tracking-wider flex items-center gap-1.5">
              <Sparkles size={14} className="text-accent-indigo" />
              <span>Smart Planning Advice</span>
            </h3>
            <p className="text-[11px] text-gray-400 leading-relaxed">
              LastMinute AI respects your body's organic rhythms. Your current profile leverages a{" "}
              <span className="text-accent-indigo font-bold capitalize">{prefs.energyPattern} Peak</span>.
            </p>
            <p className="text-[11px] text-gray-400 leading-relaxed">
              High priority tasks are mapped during periods where your attention spans are estimated to peak, while routine maintenance tasks and breaks are aligned during low points.
            </p>

            <div className="pt-3 border-t border-gray-900 space-y-2">
              <h4 className="text-[10px] font-bold text-gray-500 uppercase tracking-wider">Schedule Checklist</h4>
              <div className="space-y-1.5 text-[11px] text-gray-400">
                <div className="flex items-center gap-2">
                  <div className="w-1.5 h-1.5 rounded-full bg-accent-mint" />
                  <span>Available window: {prefs.workStartHour} - {prefs.workEndHour}</span>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-1.5 h-1.5 rounded-full bg-accent-indigo" />
                  <span>Frequent breaks configured</span>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-1.5 h-1.5 rounded-full bg-accent-indigo" />
                  <span>Urgent overdue items given top-tier focus slots</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
